name: Docker Image CI for GHCR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'beta'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build and push the image
        run: |
          docker login --username danielbrendel --password ${{ secrets.GH_CONTAINER_REGISTRY }} ghcr.io
          docker buildx build . --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag ghcr.io/danielbrendel/hortusfox-web:latest --tag ghcr.io/danielbrendel/hortusfox-web:${{ github.ref_name }} --push